/**
Email: longpv@runsystem.net
*/
export const FETCH_LIST_CLOSING_MONTH = 'FETCH_LIST_CLOSING_MONTH';
export const FETCH_LIST_CLOSING_MONTH_SUCCESS = 'FETCH_LIST_CLOSING_MONTH_SUCCESS';
export const FETCH_LIST_CLOSING_MONTH_FAILED = 'FETCH_LIST_CLOSING_MONTH_FAILED';
//
export const FETCH_LIST_ACTIVE_CLOSING_MONTH = 'FETCH_LIST_ACTIVE_CLOSING_MONTH';
export const FETCH_LIST_ACTIVE_CLOSING_MONTH_SUCCESS = 'FETCH_LIST_ACTIVE_CLOSING_MONTH_SUCCESS';
export const FETCH_LIST_ACTIVE_CLOSING_MONTH_FAILED = 'FETCH_LIST_ACTIVE_CLOSING_MONTH_FAILED';