export const FETCH_CONFIGS = 'FETCH_CONFIGS';
export const FETCH_CONFIGS_SUCCESS = 'FETCH_CONFIGS_SUCCESS';
export const FETCH_CONFIGS_FAILED = 'FETCH_CONFIGS_FAILED';

export const FETCH_CONFIGS_UPDATE = 'FETCH_CONFIGS_UPDATE';
export const FETCH_CONFIGS_UPDATE_SUCCESS = 'FETCH_CONFIGS_UPDATE_SUCCESS';
export const FETCH_CONFIGS_UPDATE_FAILED = 'FETCH_CONFIGS_UPDATE_FAILED';

export const FETCH_CONFIGS_CREATE = 'FETCH_CONFIGS_CREATE';
export const FETCH_CONFIGS_CREATE_SUCCESS = 'FETCH_CONFIGS_CREATE_SUCCESS';
export const FETCH_CONFIGS_CREATE_FAILED = 'FETCH_CONFIGS_CREATE_FAILED';
