export const FETCH_LOGIN = 'FETCH_LOGIN';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILED = 'FETCH_LOGIN_FAILED';

export const LOGIN_OUT = 'LOGIN_OUT';
export const LOGIN_OUT_SUCCESS = 'LOGIN_OUT_SUCCESS';
export const LOGIN_OUT_FAILED = 'LOGIN_OUT_FAILED';

export const FETCH_VERIFY_MAIL = 'FETCH_VERIFY_MAIL';
export const FETCH_VERIFY_MAIL_SUCCESS = 'FETCH_VERIFY_MAIL_SUCCESS';
export const FETCH_VERIFY_MAIL_FAILED = 'FETCH_VERIFY_MAIL_FAILED';


export const FETCH_VERIFY_CODE = 'FETCH_VERIFY_CODE';
export const FETCH_VERIFY_CODE_SUCCESS = 'FETCH_VERIFY_CODE_SUCCESS';
export const FETCH_VERIFY_CODE_FAILED = 'FETCH_VERIFY_CODE_FAILED';
